launch=gmysql

# 추후 MariaDB(MySQL호환) 접속정보로 교체
gmysql-host=PDNS_DB_HOST_OR_IP
gmysql-port=3306
gmysql-user=PDNS_DB_USER
gmysql-password=PDNS_DB_PASS
gmysql-dbname=PDNS_DB_NAME

# API / Webserver (옵션)
api=yes
api-key=pdns-api-key-change-me
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0

# Listen
disable-axfr=no
gmysql-dnssec=yes
default-soa-content=ns1.test.internal hostmaster.test.internal 0 10800 3600 604800 3600
# 디폴트 soa는 원하는 이름으로 변경하여 사용

local-address=0.0.0.0
local-port=53

loglevel=4
disable-syslog=yes